name: CustomMobs
version: 4.2
authors: [HellFirePvP, VitorMac10]
softdepend: [WorldEdit, WorldGuard, Multiverse-Core, MultiWorld]

main: de.hellfirepvp.CustomMobs

commands:
  cmob:
    description: Main-Cmd
    usage: /cmob
  ccmob:
    description: Console-and-Player Command
    usage: /ccmob
  cspawn:
    description: WorldSpawning-Specification Command
    usage: /cspawn
  crespawn:
    description: Respawn-Timer command
    usage: /crespawn
  ccontrol:
    description: FullControl command
    usage: /ccontrol
  cai:
    description: AI command
    usage: /cai
  cnbt:
    description: NBT Modification command
    usage: /cnbt
